manifest:
  projects:
    - name: zephyr
      url: https://github.com/TexasInstruments/simplelink-zephyr
      revision: v3.7.0-ti-9.10.04
      clone-depth: 1
      import:
        name-allowlist:
          - cmsis
          - mcuboot
          - simplelink-hal_ti
          - tinycrypt
          - zcbor

  self:
    path: modules/lib/spotflow
