manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.4.0
      clone-depth: 1
      import:
        name-allowlist:
          - cmsis_6
          - hal_silabs
          - mbedtls
          - mcuboot
          - mldsa-native
          - tf-psa-crypto
          - zcbor

  self:
    path: modules/lib/spotflow
