#ifndef SPOTFLOW_OTA_LIMITS_H
#define SPOTFLOW_OTA_LIMITS_H

#ifdef __cplusplus
extern "C" {
#endif

#define SPOTFLOW_OTA_ARTIFACT_SLUG_MAX_LENGTH 32
#define SPOTFLOW_OTA_ARTIFACT_URL_MAX_LENGTH 128
#define SPOTFLOW_OTA_ARTIFACT_SECRET_MAX_LENGTH 24
#define SPOTFLOW_OTA_ARTIFACT_VERSION_MAX_LENGTH 64

#ifdef __cplusplus
}
#endif

#endif /* SPOTFLOW_OTA_LIMITS_H */
