#ifndef SPOTFLOW_PROCESSOR_H
#define SPOTFLOW_PROCESSOR_H

#ifdef __cplusplus
extern "C" {
#endif

#if CONFIG_SPOTFLOW_MQTT_THREAD_CUSTOM_PRIORITY
#define SPOTFLOW_MQTT_THREAD_PRIORITY CONFIG_SPOTFLOW_MQTT_THREAD_PRIORITY
#else
#define SPOTFLOW_MQTT_THREAD_PRIORITY K_LOWEST_APPLICATION_THREAD_PRIO
#endif


void spotflow_start_mqtt(void);

#ifdef __cplusplus
}
#endif

#endif /* SPOTFLOW_PROCESSOR_H */
